// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB3UWz-OW56fRco15vp2XHUMU2FWVfWBU',
    appId: '1:387504232546:web:7d25ffc7c9d0247feb993b',
    messagingSenderId: '387504232546',
    projectId: 'supamemo-b9bd8',
    authDomain: 'supamemo-b9bd8.firebaseapp.com',
    storageBucket: 'supamemo-b9bd8.appspot.com',
    measurementId: 'G-G5CYTENQ65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANeJ1JtGnEFrof9pebsGle6rvZl_F-73Y',
    appId: '1:387504232546:android:ac318c51ca2dd76aeb993b',
    messagingSenderId: '387504232546',
    projectId: 'supamemo-b9bd8',
    storageBucket: 'supamemo-b9bd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYe16NuMK6FXhJESmOuZ7gH49NRap0yp8',
    appId: '1:387504232546:ios:3741c355dd2b74c1eb993b',
    messagingSenderId: '387504232546',
    projectId: 'supamemo-b9bd8',
    storageBucket: 'supamemo-b9bd8.appspot.com',
    iosClientId: '387504232546-emkqmrbbbd2kn4frrk3ea3lhsmr02mfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.supamemo',
  );
}
